name = "chickenroadbonus-review-com"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=chickenroadbonus-review.com"
HMAC_KEY = "9b76dd83ba80ca39c3ed4979868a16df9fbea65b064e81acc665479cb09229b0"
COOKIE_NAME = "dsf"
PLAY_PATH = "try-now"
BUTTON_ID = "pf6f814b97f4615f3b1e6d1611540c695"
GATE_SALT = "5a59590d6a4e2ead"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "vu95"
CTA_SELECTOR = ".play-button"
